### ISSUE TITLE
SameSite attribute warning

### ISSUE THREAD

**Issue by carlosalvidrez** [VeliovGroup/Meteor-Cookies#16]
Hi guys, are you by any change planning a release to adopt this recommendation/warning triggered in Chrome when creating cookies using your package?... 

"cookie associated with a cross-site resource"  "was set without the `SameSite` attribute"

Please let me know.
Thanks!!

**Comment by dr-dimitru** [comment]
Hello @carlosalvidrez ,

1. It was addressed in our latest release [`v2.6.0`](https://github.com/VeliovGroup/Meteor-Cookies/releases/tag/2.6.0);
2. And added to the [`.set()` methods docs](https://github.com/VeliovGroup/Meteor-Cookies#cookiessetkey-value-opts-isomorphic);
3. Please follow our [issue template](https://github.com/VeliovGroup/Meteor-Cookies/blob/master/.github/ISSUE_TEMPLATE) when opening a new ticket.

Feel free to close it in case if the issue is solved on your end.

**Comment by carlosalvidrez** [comment]
It worked thank you!

**Comment by dr-dimitru** [comment]
@carlosalvidrez I'm glad we figured it out that quickly

Please support this project with:
 - Star this package on GitHub;
 - Take a look on our [ostr.io project](https://ostr.io);
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Support [via patreon](https://patreon.com/dr_dimitru);
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
