### ISSUE TITLE
Object cookie turns into "[object Object]" after reloading the page

### ISSUE THREAD

**Issue by carlosalvidrez** [VeliovGroup/Meteor-Cookies#9]
Hi there, I'm experiencing an issue with a cookie holding a simple JavaScript object. It works well up until I refresh the page, when I do, I find the value to have turned into a string, literally: "[object Object]"... seems like there is some sort of implicit casting to string.

Any experience or general guidance when handling objects?

Using Meteor 1.7 on MacOS, latest version of ostrio:cookies, this is a client-side-only cookie.

### I'm having an issue:
  - Give an expressive description of what is went wrong
  - Version of `ostrio:cookies` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Is it *Client* or *Server* issue?
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  - If you're getting an error (exception), please provide full error log (output in console) as file or screenshot

**Comment by dr-dimitru** [comment]
Hello @carlosalvidrez ,

Could you please post exact code you're using to set a Cookie and to read it.

**Comment by dr-dimitru** [comment]
Confirmed as a [`bug`], release coming soon

**Comment by dr-dimitru** [comment]
Hello @carlosalvidrez ,

Thank you for reporting about this issue, turns out to be a big bug 🕷😬
Update is delivered in [`v2.3.0`](https://github.com/VeliovGroup/Meteor-Cookies/releases/tag/2.3.0). Please update to the latest release, and let me know how is it working on your end.

Also I would like to mention [`ClientStorage` package](https://www.npmjs.com/package/ClientStorage), which may suit your needs better.
